### ISSUE TITLE
`fsevents` npm errors

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme#137]
When trying to compile 3d6ce9622f6d5b6c700b87c02c4f637a2dd9169b using...

* i386 Ventura 13.5.2
* node versions
   * v10.14.0
   * v10.20.1
   * v10.24.1
   * v14.21.3

...we get the following errors:

Key errors:
* `> fsevents@1.2.9 install /Users/loh/dev/inq-seeds/boilerplate/node_modules/fsevents`
* `node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@10.20.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) `
* `ValueError: invalid mode: 'rU' while trying to load binding.gyp`

Full Listing
```
clickr:boilerplate loh$ npm ci

> fsevents@1.2.9 install /Users/loh/dev/inq-seeds/boilerplate/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v64-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@10.20.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
Traceback (most recent call last):
  File "/Users/loh/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/Users/loh/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/Users/loh/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/Users/loh/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/Users/loh/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/loh/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/Users/loh/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/loh/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/loh/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 22.6.0
gyp ERR! command "/Users/loh/.nvm/versions/node/v10.20.1/bin/node" "/Users/loh/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/loh/dev/inq-seeds/boilerplate/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/loh/dev/inq-seeds/boilerplate/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /Users/loh/dev/inq-seeds/boilerplate/node_modules/fsevents
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/loh/.nvm/versions/node/v10.20.1/bin/node /Users/loh/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/loh/dev/inq-seeds/boilerplate/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/loh/dev/inq-seeds/boilerplate/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/loh/dev/inq-seeds/boilerplate/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 22.6.0
node-pre-gyp ERR! command "/Users/loh/.nvm/versions/node/v10.20.1/bin/node" "/Users/loh/dev/inq-seeds/boilerplate/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/loh/dev/inq-seeds/boilerplate/node_modules/fsevents
node-pre-gyp ERR! node -v v10.20.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/loh/.nvm/versions/node/v10.20.1/bin/node /Users/loh/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/loh/dev/inq-seeds/boilerplate/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/loh/dev/inq-seeds/boilerplate/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
```

**Comment by benloh** [comment]
The workaround seems to be to use `v10.9.0`.  `fsevents` will compile without errors.

Interestingly using `v10.9.0` it still has complaints about the binary not being found, but it successfully falls back.

```
> fsevents@1.2.9 install /Users/loh/tmp/meme/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v64-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
```
