### ISSUE TITLE
BUG: Dragging "Export MZIP" produces `ReferenceError: MessagePort is not defined`

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme#87]
When dragging "EXPORT MZIP" from the Electron app, the following error occurs:

"A JavaScript error occurred in the main process:"
```
Uncaught Exception:
ReferenceError: MessagePort is not defined
at EventEmitter.ipcMain.on.ipcEvent (/Users/loh/dev/inq-seeds/boilerplate/dist/meme-darwin-x64/meme.app/Contents/Resources/app/console/console-main.js:120:19)
at EventEmitter.emit (events.js:182:13)
at WebContents.<anonymous> (/Users/loh/dev/inq-seeds/boilerplate/dist/meme-darwin-x64/meme.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
at WebContents.emit (events.js:182:13)
```

![screenshot_1248](https://github-attachments-inquirium.s3.amazonaws.com/659921876/eb174138d31384a433ec37ee1725ad86f8c2c8d1f65cc421ecf8f6a037e259bb/screenshot_1248.png)

# To Reproduce
1. `nvm use`
2. `npm run package`
3. Start `meme.app` in the `/dist` folder.
4. Make sure you allow the app access to files and documents when the `"meme.app" would like to access files in your Documents folder" appears.
5. Click the "EXPORT MZIP" button in the Electron app -- nothing happens.
6. Drag the "EXPORT MZIP" button to a folder -- the error is displayed.

**Comment by benloh** [comment]
The problem is that the `RuntimePath` in `server-archive.js` points to the old runtime folder.  It needs to point to the new runtime folder in `/Documents/MEME/db`.

We should probably make that some kind of application-wide constant.

**Comment by benloh** [comment]
@scott.campion Just letting you know: I think this came up while I was demoing.  The culprit is the runtime path changes in `server-archive.js`.  Should be an easy fix.  But we probably want to fix this once and for all across all the server variants.

**Comment by benloh** [comment]
mentioned in commit 8d317cbb7895deac16c76bccbcb0fe7f17eb4255

**Comment by benloh** [comment]
8d317cbb should fix this.
